//! Emit a src/zobrist_table.zig file that is a splitmix64-seeded 781 entry Zobrist table.

// Initially I had this created at runtime which would have been a lot of overhead, so I went with
// comptime, that required setting the comptime loop limit, so I asked AI if it had a better
// approach and it suggested a generator like this, I've never really tried writing anything like
// this so I YOLOed it. Practically you'd set the comptime limit and generate it at comp time.

// OUTPUT_PATH is resolved against cwd(); invoke from the project root.

const std = @import("std");
const Io = std.Io;

const GENERATOR_VERSION: u32 = 1;
const GENERATION_DATE: []const u8 = "2026-04-17";
// SEED is the one-shot splitmix64 generation input; frozen — do not change without a new DEC entry.
const SEED: u64 = 0x13AF;
const OUTPUT_PATH = "src/zobrist_table.zig";

// 12 piece-types × 64 squares = 768, 4 castling rights, 8 en-passant files, plus 1 side-to-move
// = 781.
const TABLE_SIZE: usize = 781;
const PIECE_SQUARE_BASE: usize = 0;
const CASTLING_BASE: usize = 768;
const EP_FILE_BASE: usize = 772;
const SIDE_TO_MOVE_INDEX: usize = 780;

/// Generates the next splitmix64 number given the state.
fn splitmix64_next(state: *u64) u64 {
    // Zero is known to lead to not very good generation so we're going to assert that here.
    std.debug.assert(state.* != 0);
    // Since the numbers can grow quite big we're using the wrap around arithmetic operators.
    state.* +%= 0x9E3779B97F4A7C15;
    var z = state.*;
    z = (z ^ (z >> 30)) *% 0xBF58476D1CE4E5B9;
    z = (z ^ (z >> 27)) *% 0x94D049BB133111EB;
    return z ^ (z >> 31);
}

fn write_hex_u64(writer: *Io.Writer, value: u64) !void {
    const n0: u16 = @intCast((value >> 48) & 0xFFFF);
    const n1: u16 = @intCast((value >> 32) & 0xFFFF);
    const n2: u16 = @intCast((value >> 16) & 0xFFFF);
    const n3: u16 = @intCast(value & 0xFFFF);
    try writer.print("0x{x:0>4}_{x:0>4}_{x:0>4}_{x:0>4}", .{ n0, n1, n2, n3 });
}

fn write_table(writer: *std.Io.Writer) !void {
    std.debug.assert(SEED != 0);

    // Write the header
    try writer.writeAll(
        \\//! Holds the 781 sized Zobrist table generated by tools/zobrist_generator.zig.
        \\
        \\// Generated by: tools/zobrist_generator.zig
        \\
    );

    try writer.print("// Generator version: {d}\n", .{GENERATOR_VERSION});
    try writer.writeAll("// SEED: ");
    try write_hex_u64(writer, SEED);
    try writer.writeAll("\n");
    try writer.print("// Generated on: {s}\n", .{GENERATION_DATE});
    try writer.writeAll(
        \\// Entries: 781 ([0..768) piece-square, [768..772) castling, [772..780) ep-file, [780] side-to-move)
        \\//
        \\// DO NOT HAND-EDIT. To regenerate:
        \\//   zig run tools/zobrist_generator.zig    (run from project root)
        \\
        \\const std = @import("std");
        \\
        \\pub const PIECE_SQUARE_BASE: usize = 0;
        \\pub const CASTLING_BASE: usize = 768;
        \\pub const EP_FILE_BASE: usize = 772;
        \\pub const SIDE_TO_MOVE_INDEX: usize = 780;
        \\
        \\pub const TABLE: [781]u64 = .{
        \\
    );

    var state: u64 = SEED;
    var i: usize = 0;
    while (i < TABLE_SIZE) : (i += 1) {
        const value = splitmix64_next(&state);
        try writer.writeAll("    ");
        try write_hex_u64(writer, value);
        try writer.writeAll(",\n");
    }
    std.debug.assert(i == TABLE_SIZE);

    try writer.writeAll(
        \\};
        \\
        \\pub const SIDE_TO_MOVE: u64 = TABLE[SIDE_TO_MOVE_INDEX];
        \\
        \\comptime {
        \\    std.debug.assert(TABLE.len == 781);
        \\}
        \\
        \\test "zobrist TABLE has Polyglot-canonical 781 entries in four named segments" {
        \\    try std.testing.expectEqual(@as(usize, 781), TABLE.len);
        \\    try std.testing.expectEqual(TABLE[SIDE_TO_MOVE_INDEX], SIDE_TO_MOVE);
        \\    try std.testing.expectEqual(@as(usize, 768), CASTLING_BASE - PIECE_SQUARE_BASE);
        \\    try std.testing.expectEqual(@as(usize, 4), EP_FILE_BASE - CASTLING_BASE);
        \\    try std.testing.expectEqual(@as(usize, 8), SIDE_TO_MOVE_INDEX - EP_FILE_BASE);
        \\}
        \\
    );
}

pub fn main(init: std.process.Init) !void {
    std.debug.assert(GENERATOR_VERSION >= 1);
    const io = init.io;

    // Preflight: verify cwd is the project root by probing for build.zig. OUTPUT_PATH is
    // resolved against cwd() — running from the wrong directory would silently truncate a
    // sibling src/zobrist_table.zig.
    const sentinel = Io.Dir.cwd().openFile(io, "build.zig", .{}) catch |err| {
        std.debug.print("error: invoke from project root (cwd must contain build.zig): {}\n", .{err});
        return err;
    };
    sentinel.close(io);

    const file = try Io.Dir.cwd().createFile(io, OUTPUT_PATH, .{});
    defer file.close(io);

    var file_buffer: [4096]u8 = undefined;
    var file_writer = file.writer(io, &file_buffer);
    const writer = &file_writer.interface;

    try write_table(writer);
    try writer.flush();
    std.debug.assert(writer.end == 0);
}
